### ISSUE TITLE
Error during install in windows

### ISSUE THREAD

**Issue by Jerrk** [jaruba/PowderWeb#40]
i extract .zip into PowderWeb-master

open cmd in location

apm install

now i run into errors

```
> window-prebuilt@0.0.1 postinstall C:\PowderWeb-master\node_modules\window-prebuilt
> node install.js

fs.js:151
    throw new ERR_INVALID_CALLBACK(cb);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:151:11)
    at Object.rename (fs.js:644:14)
    at WriteStream.<anonymous> (C:\PowderWeb-master\node_modules\window-prebuilt\install.js:28:10)
    at WriteStream.emit (events.js:311:20)
    at internal/fs/streams.js:241:14
    at FSReqCallback.oncomplete (fs.js:154:23) {
  code: 'ERR_INVALID_CALLBACK'
}
```

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! window-prebuilt@0.0.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the window-prebuilt@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jerrk\AppData\Roaming\npm-cache\_logs\2020-03-17T12_04_33_227Z-debug.log

C:\PowderWeb-master>
```

full logs here
[2020-03-17T12_04_33_227Z-debug.log](https://github.com/jaruba/PowderWeb/files/4343362/2020-03-17T12_04_33_227Z-debug.log)

**Comment by jaruba** [comment]
Is there a reason why you are trying to build it yourself?

You can just use the prebuilts from the releases page:
https://github.com/jaruba/PowderWeb/releases

**Comment by Jerrk** [comment]
Haha i was just reading the readme and going through the install steps, i don't know why but the releases page completely slipped my mind.

Installed it now and it seems to work as it should :)

**Comment by jaruba** [comment]
Glad to hear it.
