### ISSUE TITLE
Binary problem

### ISSUE THREAD

**Issue by programerr01** [jaruba/PowderWeb#69]
when i run 
````bash
npm run start-back
````
it say's 
```bash
Gtk-Message: 20:13:45.014: Failed to load module "canberra-gtk-module"
App threw an error during load
ReferenceError: ytdlBinary is not defined
    at Object.<anonymous> (/home/a/PowderWeb/node_modules/youtube-dl/lib/youtube-dl.js:33:20)
    at Object.<anonymous> (/home/a/PowderWeb/node_modules/youtube-dl/lib/youtube-dl.js:397:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/a/PowderWeb/server/ytdl.js:2:14)
A JavaScript error occurred in the main process
Uncaught Exception:
ReferenceError: ytdlBinary is not defined
    at Object.<anonymous> (/home/a/PowderWeb/node_modules/youtube-dl/lib/youtube-dl.js:33:20)
    at Object.<anonymous> (/home/a/PowderWeb/node_modules/youtube-dl/lib/youtube-dl.js:397:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/a/PowderWeb/server/ytdl.js:2:14)
(node:53272) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

(electron:53272): Pango-ERROR **: 20:13:47.081: Harfbuzz version too old (1.3.1)



```

**Comment by jaruba** [comment]
I've been seeing a lot of this error lately, the gist is that `npm install` failed with some errors. Delete the `node_modules` folder, do `npm install` again and paste the error here.

I'll try to look into it tonight or tomorrow, it may be because `youtube-dl` was recently removed from github, but can't know until I debug it thoroughly.

**Comment by programerr01** [comment]
Still the same error shows up.

**Comment by jaruba** [comment]
I meant the errors that u get from `npm install` not from `npm run start-back`, the error u pasted above is a consequence from the error that `npm install` gives.

**Comment by programerr01** [comment]
this is what i get from  ``` npm install ```
```bash 
npm WARN deprecated react-router-redux@5.0.0-alpha.9: This project is no longer maintained.

> phantomjs-prebuilt@2.1.16 install /home/a/PowderWeb/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /home/a/PowderWeb/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1605112010501/phantomjs-2.1.1-linux-x86_64 -> /home/a/PowderWeb/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/a/PowderWeb/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> core-js@2.6.11 postinstall /home/a/PowderWeb/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js-pure@3.7.0 postinstall /home/a/PowderWeb/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> styled-components@3.4.10 postinstall /home/a/PowderWeb/node_modules/grid-styled/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0

Use styled-components at work? Consider supporting our development efforts at opencollective.com/styled-components

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/a/PowderWeb/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> duti-prebuilt@https://github.com/jaruba/duti-prebuilt/tarball/master postinstall /home/a/PowderWeb/node_modules/duti-prebuilt
> node install.js


> easy-ffmpeg@https://github.com/jaruba/easy-ffmpeg/tarball/master postinstall /home/a/PowderWeb/node_modules/easy-ffmpeg
> node install.js


> electron@1.6.7 postinstall /home/a/PowderWeb/node_modules/electron
> node install.js


> subtitles-thread@https://github.com/jaruba/subtitles-thread/tarball/master postinstall /home/a/PowderWeb/node_modules/subtitles-thread
> node install.js


> torrent-thread@https://github.com/jaruba/torrent-thread/tarball/master postinstall /home/a/PowderWeb/node_modules/torrent-thread
> node install.js

(node:57121) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit

> window-prebuilt@https://github.com/jaruba/window-prebuilt/tarball/master postinstall /home/a/PowderWeb/node_modules/window-prebuilt
> node install.js


> youtube-dl@https://github.com/jaruba/node-youtube-dl/tarball/master postinstall /home/a/PowderWeb/node_modules/youtube-dl
> node ./scripts/download.js

Error: Response Error: 404
    at Request.get [as _callback] (/home/a/PowderWeb/node_modules/youtube-dl/lib/downloader.js:60:65)
    at Request.self.callback (/home/a/PowderWeb/node_modules/youtube-dl/node_modules/request/request.js:200:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/a/PowderWeb/node_modules/youtube-dl/node_modules/request/request.js:1067:10)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/a/PowderWeb/node_modules/youtube-dl/node_modules/request/request.js:988:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
npm WARN powder-web@0.9.0 No license field.
npm WARN The package npm-run-all is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2465 packages from 2343 contributors and audited 2476 packages in 168.27s
found 214 vulnerabilities (111 low, 42 moderate, 59 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details


```

**Comment by jaruba** [comment]
There's our error, we get a HTTP `404` "Not found" error when trying to install `youtube-dl`, so yes, i think this is deeply related to the `youtube-dl` project being taken off GitHub. Thanks, I'll investigate things further.

**Comment by programerr01** [comment]
update me if you get any.

**Comment by jaruba** [comment]
@programerr01 I made some changes to the `youtube-dl` module I'm using, it installs fine now for me. I will close this issue, if you still have problems installing you can reopen it.
