### ISSUE TITLE
Error  with youtube-dl 

### ISSUE THREAD

**Issue by programerr01** [jaruba/PowderWeb#70]
```
> youtube-dl@https://github.com/jaruba/node-youtube-dl/tarball/master postinstall /home/yogesh/PowderWeb/node_modules/youtube-dl
> node ./scripts/download.js

/home/yogesh/PowderWeb/node_modules/youtube-dl/lib/downloader.js:86
    if (!isOverwrite) {
    ^

ReferenceError: isOverwrite is not defined
    at downloader (/home/yogesh/PowderWeb/node_modules/youtube-dl/lib/downloader.js:86:5)
    at Object.<anonymous> (/home/yogesh/PowderWeb/node_modules/youtube-dl/scripts/download.js:3:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm WARN eslint-config-airbnb@17.1.0 requires a peer of eslint-plugin-jsx-a11y@^6.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsx-a11y@5.1.1 requires a peer of eslint@^2.10.2 || ^3 || ^4 but none is installed. You must install peer dependencies yourself.
npm WARN powder-web@0.9.0 No license field.
npm WARN The package npm-run-all is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl@https://github.com/jaruba/node-youtube-dl/tarball/master postinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-dl@https://github.com/jaruba/node-youtube-dl/tarball/master postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

> youtube-dl@https://github.com/jaruba/node-youtube-dl/tarball/master postinstall /home/yogesh/PowderWeb/node_modules/youtube-dl
> node ./scripts/download.js

/home/yogesh/PowderWeb/node_modules/youtube-dl/lib/downloader.js:86
    if (!isOverwrite) {
    ^

ReferenceError: isOverwrite is not defined
    at downloader (/home/yogesh/PowderWeb/node_modules/youtube-dl/lib/downloader.js:86:5)
    at Object.<anonymous> (/home/yogesh/PowderWeb/node_modules/youtube-dl/scripts/download.js:3:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm WARN eslint-config-airbnb@17.1.0 requires a peer of eslint-plugin-jsx-a11y@^6.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsx-a11y@5.1.1 requires a peer of eslint@^2.10.2 || ^3 || ^4 but none is installed. You must install peer dependencies yourself.
npm WARN powder-web@0.9.0 No license field.
npm WARN The package npm-run-all is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl@https://github.com/jaruba/node-youtube-dl/tarball/master postinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-dl@https://github.com/jaruba/node-youtube-dl/tarball/master postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by jaruba** [comment]
Ok, I set it to always overwrite, try again, if the problem persists you can reopen the issue.
